### GET ALL ITEMS

GET http://localhost:5000/items
Content-Type: application/json

### GET Single ITEM

GET http://localhost:5000/items/1
Content-Type: application/json

### ADD ITEM

POST http://localhost:5000/items
Content-Type: application/json

{
  "name": "New Item"
}
